name: 02 - Eventos
on: - push:
    - pull_request:
    - schedule:
      - cron: "50 16 * * *",
      - cron: "55 16 * * *",
    - workflow_dispatch:
jobs:
  echo: 
    runs-on: ubuntu-latest
    steps:          
      - name: ShowTrigger
        run: |
           echo "Event name: ${{ github.event_name }}"